### ISSUE TITLE
有没有考虑使用electron写一个桌面端呢，总感觉浏览器性能不咋滴

### ISSUE THREAD

**Issue by zhanghaifei1997** [huhaibiao/video-edit-demo#3]

**Comment by huhaibiao** [comment]
可以

**Comment by zhanghaifei1997** [comment]
加油，坐等借鉴代码时刻

**Comment by ls10097714** [comment]
桌面端版本的项目有写吗

**Comment by huhaibiao** [comment]
> 桌面端版本的项目有写吗

可以使用electron开发哦，咋个说？

**Comment by ls10097714** [comment]
> > 桌面端版本的项目有写吗
> 
> 可以使用electron开发哦，咋个说？

没有electron开发经验，想短时间能用起来，哈哈哈想借鉴一下

**Comment by huhaibiao** [comment]
想短时间用起来，这。。。。，作什么不都得研发和投入 啊，这项目我就投入了5天业余时间，还是一家公司的面试题，没有后续的继续投入的资源啊😂

**Comment by ls10097714** [comment]
> 想短时间用起来，这。。。。，作什么不都得研发和投入 啊，这项目我就投入了5天业余时间，还是一家公司的面试题，没有后续的继续投入的资源啊😂

哈哈哈，好的明白了，我去研究研究，有结果了回复你

**Comment by huhaibiao** [comment]
> > 想短时间用起来，这。。。。，作什么不都得研发和投入 啊，这项目我就投入了5天业余时间，还是一家公司的面试题，没有后续的继续投入的资源啊😂
> 
> 哈哈哈，好的明白了，我去研究研究，有结果了回复你

好， 有啥不懂 可以问哦，我会的话可以研究研究看看，加油

**Comment by ls10097714** [comment]
> > > 想短时间用起来，这。。。。，作什么不都得研发和投入 啊，这项目我就投入了5天业余时间，还是一家公司的面试题，没有后续的继续投入的资源啊😂
> > 
> > 
> > 哈哈哈，好的明白了，我去研究研究，有结果了回复你
> 
> 好， 有啥不懂 可以问哦，我会的话可以研究研究看看，加油
好的，哈哈哈，多多指教
