### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wangyalong4** [huhaibiao/video-edit-demo#4]
依赖安装不了
(node:9276) [DEP0170] DeprecationWarning: The URL http://your-proxy-server:port is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2872) [DEP0170] DeprecationWarning: The URL http://your-proxy-server:port is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! code ERR_INVALID_URL
npm ERR! Invalid URL
 报错信息

**Comment by huhaibiao** [comment]
更换网络安装依赖试试

**Comment by oniontang** [comment]
项目中使用"@ffmpeg/ffmpeg": "^0.11.6"版本会导致“shareArrayBuffer not defined”的问题，然后我这边更新了ffmpeg的版本，现在使用的版本是“@ffmpeg/ffmpeg": "^0.12.9”，然后提取视频帧的时候，效率比您这边的要低十多倍，体验非常差，关于视频取帧这块是不是本项目中做了什么优化？

**Comment by huhaibiao** [comment]
> 项目中使用"@ffmpeg/ffmpeg": "^0.11.6"版本会导致“shareArrayBuffer not defined”的问题，然后我这边更新了ffmpeg的版本，现在使用的版本是“@ffmpeg/ffmpeg": "^0.12.9”，然后提取视频帧的时候，效率比您这边的要低十多倍，体验非常差，关于视频取帧这块是不是本项目中做了什么优化？

你的视频取帧用的是另外的代码？我觉得这些问题应该和这个库的版本关系不大

**Comment by wangyalong4** [comment]
感谢回复  解决了
